### ISSUE TITLE
Proposal: change `incomplete-ratings-obligations` --> `unsatisfied-ratings-obligations`

### ISSUE THREAD

**Issue by catkins-miso** [trolie/spec#104]
"incomplete" is easily confused as implying TROLIE accepts partial forecasts per facility

**Comment by catkins-miso** [comment]
@getorymckeag please label this as spec change or close it as "won't do". I think it has merit, but I don't have a sense of the cost of change at this point.

**Comment by getorymckeag** [comment]
I don't feel this is necessary.
