### ISSUE TITLE
Day/Night variations for seasonal ratings

### ISSUE THREAD

**Issue by travis-qualus** [trolie/spec#123]
Many TOs have day and night variations for their AAR seasonal ratings.  The daytime ratings use solar heating assumptions, which can be significant in summer.

The current seasonal ratings format doesn't seem to support that?

One option is to define that as a different season (summer-day, summer-night), but then you'd also need a way to define the start/end hour of sunlight for that season definition - or better yet, the market would use known solar calendars to choose whether day or night ratings are in effect.

**Comment by catkins-miso** [comment]
This is an excellent point. Thank you for bringing it up again. I've reached out to folks internally one of whom participates in the NATF 881 forum. As an interop spec, I am included to believe this should be accommodated though my organization does not use this.

**Comment by travis-qualus** [comment]
Curious how MISO handles the day/night differences in solar radiation heating effects on the line, unless you just use a conservative assumption for the entire day?

**Comment by crossMISO** [comment]
Hi @travis-qualus!  Thank you for bringing up this point.  Regarding industry recommendations for seasonal ratings calculation, my understanding is the industry doesn't specifically recommend calculating seasonal day or night ratings, but some Transmission Owners do so.  For interoperability, it seems prudent to include the ability to exchange seasonal day or night ratings if the Ratings Provider does calculate those ratings and others need them, but that should be optional as not all Transmission Owners do so.   

For MISO, we leave the calculation of the solar radiation heating on the equipment and facility ratings up to the Transmission Owner.   At a minimum, the Transmission Owner needs to calculate the AARs for daytime and nighttime, which could use conservative (in terms of lower rating result) heating values for those time periods.   Some may go beyond the Order 881 requirements and calculate the solar heating effects based on the hourly sun azimuth.  Per the Order 881, they have to minimally account for sunrise and sunset times monthly in AAR calculations, and many may choose to do so more frequently like daily.

**Comment by travis-qualus** [comment]
To the extent the TOs are expected to provide hourly ratings anyway, I agree it's on them to determine how to incorporate solar heating assumptions in each given hour based on the solar hours of each month.

It wasn't clear whether MISO (or other RCs) would also want seasonal ratings from the TOs to use as backup values if the hourly ratings are not available for some technical reason.

**Comment by catkins-miso** [comment]
> It wasn't clear whether MISO (or other RCs) would also want seasonal ratings from the TOs to use as backup values if the hourly ratings are not available for some technical reason.

It's my understanding PJM uses day/night seasonal ratings, for example, but not all RCs do so. Regardless, I wanted to say definitively that you are right that "[RCs] want seasonal ratings from the TOs to use as backup values if the hourly ratings are not available for some technical reason." In MISO's case we would use the most conservative seasonal rating, but I'm hearing unanimity that TROLIE needs to support day/night for interop.

**Comment by getorymckeag** [comment]
I agree, and this is timely since we're starting work on firming up the seasonal rating spec anyway.  I think there is enough agreement already here, promoting this to a spec change and moving it to the seasonal milestone.
