### ISSUE TITLE
forecasted static ratings

### ISSUE THREAD

**Issue by catkins-miso** [trolie/spec#127]
When we consider all the use cases for forward ops, there are three distinct data needs:

- Forecasts including AARs, which beyond 10 days (for most implementations) is equivalent to
- Forecasts *not* including AARs, which if there are no scheduled derates/overrides looks exactly like
- Seasonal Ratings Schedule

The spec allows clients to request a forecast beyond 10 days via the `period-end` parameter. This implies that a successful response would need to impute a forecast based on seasonal ratings, temp AAR exceptions, and seasonal overrides for periods beyond 10 days.

However, there is no affordance for requesting that same information for periods fewer than 10 days out. In other words, clients cannot request the **forecasted static ratings** over the next 10 days. We have identified internal use cases at MISO for requesting this information in Ops Planning.

I believe there are interop use cases that need this too that we just haven’t touched upon yet. For example, if an RC is planning to monitor an adjacent RC's seasonal ratings in operations in case of a communications outage between the RCs, a seasonal override or an outage-driven derate in ops may not be reflected in their seasonal ratings. What they may actually need is the forecasted static rating (and associated emergency durations).

Consequently, I’d like to propose a change to the TROLIE spec to clarify the forecasted static rating semantically both as a standalone forecast that you can request, but also in the detailed response media type of the existing forecast for the periods beyond 10 days.

Based on an earlier conversation, I anticipate this quickly being moved from Discussion to Proposal, so I want to throw out a concrete change for consideration:

> Add a `static-ratings-only` Boolean parameter to the `getLimitsForecastSnapshot`.

However, we should also ensure there's a clear way to determine from the detailed limits forecast snapshot media type that a forecasted limit was determined by using a static rating not a proposal. I don't think that's the case, so this change would also require an update to that media type.

/cc @lreaves-spp

**Comment by catkins-miso** [comment]
@getorymckeag are you good with this becoming a proposal?
> I’d like to propose a change to the TROLIE spec to clarify the forecasted static rating semantically both as a standalone forecast that you can request, but also in the detailed response media type of the existing forecast for the periods beyond 10 days.

My current thinking is that there'd be a new `?static-only=true` on limits snapshot `GET`s and an indication in the provenance of the detailed snapshot that a static rating was used.

**Comment by getorymckeag** [comment]
> @getorymckeag are you good with this becoming a proposal?
> 
> > I’d like to propose a change to the TROLIE spec to clarify the forecasted static rating semantically both as a standalone forecast that you can request, but also in the detailed response media type of the existing forecast for the periods beyond 10 days.
> 
> My current thinking is that there'd be a new `?static-only=true` on limits snapshot `GET`s and an indication in the provenance of the detailed snapshot that a static rating was used.

Yes.
