### ISSUE TITLE
Conditional seasonal ratings in TROLIE

### ISSUE THREAD

**Issue by getorymckeag** [trolie/spec#129]
There are some lines in the ISO New England footprint that can have different ratings depending on their configuration.  My understanding is that this typically applies to underwater lines that are packed tightly in trays, where certain combinations of the conductors may be turned on and off.  Switching conductors on and off obviously changes the amount of copper that can carry electrons.  However, to add additional complexity, the wires are close enough to one another that they can heat each other up as well, and the overall rating must take this into account.  Therefore, each possible combination will have a unique rating.  

When computing AARs, we currently assume that the AAR accounts for the actual or forecasted configuration of the line.  

However, for seasonal ratings, the configuration of the line cannot be forecasted.  A separate rating must be provided for each configuration.  

I propose that we take a similar strategy that we did for directional ratings: https://trolie.energy/decision-log/directional-ratings.html.  Where each configuration is simply considered a separate resource.  It would seem to match the pattern we've set so far for these corner cases.  If we're generally in agreement, I'll create an ADR like I did for directional ratings.

**Comment by catkins-miso** [comment]
I was going to ask how each condition nominated in their EMS, but it doesn't change the "inbox" principle we've been following: Every rating (continuous + emergency durations) proposed to TROLIE must be associated with a unique power system resource whose identity is assumed to be precoordinated between the sender and receiver.
