### ISSUE TITLE
Clarify resource-id versus proposal id in `proposals-considered`

### ISSUE THREAD

**Issue by catkins-miso** [trolie/spec#182]
clarify that `resource-id` from `proposals-considered` is like the SEG id, and  `source.origin-id` is like a correlation-id

**Comment by catkins-miso** [comment]
One question here @getorymckeag: "Do I use the SEG mrid as the primary resource id when I submit a proposal or the DYNELE mrid?"

Now, SEG id is effectively the Ratings Obligation identifier in TROLIE parlance, but we have not yet made the Ratings Obligation an explicit resource, but the `resource-id` in a proposal is the facility mrid, so the e.g. DYNELE mrid. 

However, in the `proposals-considered` provenance info of a limits snapshot, I think the clearinghouse provider should populate the `proposals-considered.resource-id` with the SEG id. This would be useful in debugging any mapping issues.

**Comment by getorymckeag** [comment]
> One question here @getorymckeag: "Do I use the SEG mrid as the primary resource id when I submit a proposal or the DYNELE mrid?"
> 
> Now, SEG id is effectively the Ratings Obligation identifier in TROLIE parlance, but we have not yet made the Ratings Obligation an explicit resource, but the `resource-id` in a proposal is the facility mrid, so the e.g. DYNELE mrid.
> 
> However, in the `proposals-considered` provenance info of a limits snapshot, I think the clearinghouse provider should populate the `proposals-considered.resource-id` with the SEG id. This would be useful in debugging any mapping issues.

That's exactly what we do.
