### ISSUE TITLE
change psr to resource-id in static ratings?

### ISSUE THREAD

**Issue by catkins-miso** [trolie/spec#206]
`proposal-considered` has an optional `resource-id` whereas temp AAR exceptions and seasonal overrides have `resource`, allowing for `alternate-identifiers` similar to the psr header. We should reconcile these

_Originally posted by @catkins-miso in https://github.com/trolie/spec/issues/200#issuecomment-2457207323_
            
Please see [this commit](https://github.com/trolie/spec/commit/df92f1ebaa7a7d0bc1c04f4afeff1d28b53090f3) for a concrete idea of one way to address this. I'm not sure we should lose the alternate identifiers, which is why I want you to look at it.

**Comment by getorymckeag** [comment]
Yeah I don't dig this.  The cost of losing the alternate identifiers feels wrong.
