### ISSUE TITLE
Apply standard for "Problems" in error reporting

### ISSUE THREAD

**Issue by getorymckeag** [trolie/spec#25]
Consider changing problem reporting for API errors to use the standard at https://www.rfc-editor.org/rfc/rfc7807

**Comment by caindy** [comment]
I fully support this. I'll open a PR to add it as the sole response for all 400 and 422 responses.

**Comment by caindy** [comment]
Let's adopt the newer https://www.rfc-editor.org/rfc/rfc9457 which obsoletes 7807.

**Comment by caindy** [comment]
In my hurry to get this done, I did not apply the change to all the `400 Bad Request` responses.

**Comment by caindy** [comment]
Resolved in #32
