### ISSUE TITLE
Revisit the schema for limit-provenance

### ISSUE THREAD

**Issue by caindy** [trolie/spec#47]
some specifics:
* Is a reference sufficient for `proposals-considered` and `temporary-aar-exceptions`?
* Is the presence of `override-reason` sufficient to indicate that `continuous-operating-limit` is an override?

For reference, the [initial draft](https://github.com/misoenergy/TROLIE/blob/main/openapi-spec.yml#L880-L902) had a discrete `provenance`/`coordinated-source`. The basic idea was tracking:
* When the proposal was received
* When the proposal was generated (by the provider)
* A place for the provider to identify "how" the proposed limit was generated (could the system that generated it and/or the method, like "override")

**Comment by catkins-miso** [comment]
this was addressed in #96
