### ISSUE TITLE
Improve Seasonal ratings model

### ISSUE THREAD

**Issue by getorymckeag** [trolie/spec#5]
The seasonal ratings model needs a variety of tweaks.  It has outgrown the refinements of requirements as we understand them.  
- Consider removing update capability from TROLIE.  While the ability to read seasonal ratings is definitely required for interop, the process to update them is still widely variable across ISOs.  
- Seasonal ratings must consider season schedules that may apply differently per-segment.

**Comment by catkins-miso** [comment]
close as dupe
