### ISSUE TITLE
include optional "determining factors" for `forecast-period-proposal`?

### ISSUE THREAD

**Issue by catkins-miso** [trolie/spec#61]
@getorymckeag I was relayed a specific request:
> optional fields for solar irradiance (day/night status) and temperature could be included in the TROLIE spec, to be submitted by Ratings Providers, as additional context with the rating proposal submitted by the Ratings Provider?

I think this could be easily accommodated as an option field here https://github.com/trolie/spec/blob/1.0.0-wip/docs/_data/components/schemas/forecast-limit-period.yaml#L11

We do already have support for vendor-specific extensions on the limit output:
https://github.com/trolie/spec/blob/1.0.0-wip/docs/_data/components/schemas/limit-provenance.yaml#L29

We could (should?) adopt this for inbound proposals, too, so the question comes down to if this should be a vendor extension or if determining factors should be considered first class attributes for interop. I'm inclined to support `temp` and `activeInsolation?` (or similar) as optional attributes on limits.

**Comment by catkins-miso** [comment]
Is the CIM Measurements model appropriate for this?
![image](https://github.com/trolie/spec/assets/57670484/24591d80-fb07-495f-a58c-d253807862e6)
![image](https://github.com/trolie/spec/assets/57670484/d853a40e-3f50-4852-8dae-dcfde9759cba)

**Comment by getorymckeag** [comment]
> Is the CIM Measurements model appropriate for this? ![image](https://private-user-images.githubusercontent.com/57670484/309832207-24591d80-fb07-495f-a58c-d253807862e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NzI2NjEsIm5iZiI6MTcwOTU3MjM2MSwicGF0aCI6Ii81NzY3MDQ4NC8zMDk4MzIyMDctMjQ1OTFkODAtZmIwNy00OTVmLWE1OGMtZDI1MzgwNzg2MmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE3MTI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NDA5Mjg2YjY3NGE0NDFmZDIxMDE1YjBhMTE5ZDY5MDZlZGUxY2IwM2M3ZDMxMTU0NGIzMWUwMDQwZWY4ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nKrt6tVcd8nOtbYKUbnHu6zOWTh8T3WgLjoFxDh1nfw)

For Forecasts?  I don't think I get it.  On the original question, I think that temperature and active insolation are probably good additions.  Can we think of a term more plain-spoken than "insolation" though?  I know it's precise, but 90% of the people looking at it will have to look it up nearly every time they see it.  Me included.

**Comment by catkins-miso** [comment]
> On the original question, I think that temperature and active insolation are probably good additions. Can we think of a term more plain-spoken than "insolation" though? I know it's precise, but 90% of the people looking at it will have to look it up nearly every time they see it. Me included.

In https://github.com/trolie/spec/pull/63/files I propose a very generic way to represent additional inputs, delegating the definition of conventions for input representation to a particular exchange, i.e., to the RC hosting the TROLIE instance. 

We *could* express a preference in the specification for how to represent `sun-is-shining-on-conductor as Boolean` and/or `temp-in-Fahrenheit as float`, but I think this data should be defined to be informational by this specification, so the proposed basic structure is appropriate.
