### ISSUE TITLE
consider dropping /rating-proposals/forecasts/{ratings-provider} endpoint in interop

### ISSUE THREAD

**Issue by caindy** [trolie/spec#70]
An alternate proposal for the semantics forecasts was that there was an area-wide `/ratings-proposal/forecast` that every Ratings Provider is `PATCH`ing. I documented that here https://trolie.energy/articles/forecast-windows#on-time--202-accepted (prematurely):

>As discussed in [Submitting Forecast Ratings](https://trolie.energy/example-narratives/submitting-forecasts.md), the client must PATCH the overall Ratings Forecast of the Clearinghouse Provider with their own proposal.

What are the interop use cases for `/rating-proposals/forecasts/{ratings-provider}` as a top-level resource? I'll try to enumerate some possibility and indicate why I think they are invalid.

* __Check on my proposal__: This is classic "POST-redirect-GET" territory... a UI POSTs a forecast, gets a redirect to the newly created resource URL, and GETs it for display. On the other hand, our interop use cases are API driven and use the PATCH's 202 Accepted or any of the 4xx responses to decide what to do next. From an interop perspective, by the time the PATCH is issued, the client has its own identifier for it, and they would update its submission status locally.
* __Were my ratings used as limits?__: This is data in the limits snapshot with provenance (detailed) and doesn't really line up with the semantics of the submission being a `/ratings-proposal`. Why have this info accessible two ways?
* __Authorization of proposals__: We will have to do object-level authorization in any case.

**Comment by caindy** [comment]
If this is accepted, note that we should change `ratings-proposal/forecasts` (plural, per Ratings Provider) to `ratings-proposal/forecast` (singular, `PATCH`ing the area-wide proposal).

**Comment by getorymckeag** [comment]
Agreed, drop it.  This was an artifact of when I was thinking about the "interop" scope of TROLIE in a much broader way.

**Comment by catkins-miso** [comment]
Thanks, I'll get this done first thing tomorrow.
