### ISSUE TITLE
Consider removal of missing ratings funtions

### ISSUE THREAD

**Issue by getorymckeag** [trolie/spec#8]
While detecting missing ratings is functionally important for TROLIE implementations, it is unclear if this has a clear role in interop.

**Comment by caindy** [comment]
In the first iteration of the TROLIE spec, I had the 202 Accepted response to a proposal PATCH return the outstanding Ratings Obligations for the Ratings Provider in the Forecast Window. I imagined that after sending their last patch, the Ratings Provider might assert that the outstanding (missing) obligation count should be zero. I believe being able to answer "are we done for now?" is important for interop.

**Comment by catkins-miso** [comment]
We want this functionality in TROLIE.
