### ISSUE TITLE
Remove `getLimitsForecastByPeriod`?

### ISSUE THREAD

**Issue by caindy** [trolie/spec#88]
It's probably not an interop use case anyway, but couldn't the same result can be obtained from [getLimitsForecastSnapshot](https://trolie.energy/spec#tag/Operating-Snapshots/operation/getLimitsForecastSnapshot) by using the params `period-end` = `offset-period-start` + 1, right?

![image](https://github.com/trolie/spec/assets/70229/9fa9b8bd-707a-436a-a712-a3f19015dce9)

**Comment by getorymckeag** [comment]
Yeah not needed for interop, agreed.
